name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
      with:
        node-version: 18

    - name: Setup pnpm
      uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
      with:
        version: 7
        run_install: |
          - args: [--global, gulp]
          
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
  
    - name: Build
      run: pnpm build
          
    - name: Upload build files
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
      with:
        name: build
        path: ./build/
        if-no-files-found: error
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Clone repository
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e

      - name: Download build files
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869
        with:
          name: build
          path: ./build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/
