name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
        run_install: |
          - args: [--global, gulp]
          
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
  
    - name: Build
      run: pnpm build
          
    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build/
        if-no-files-found: error
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download build files
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # tag=v2.1.0
        with:
          name: build
          path: ./build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/
